### ISSUE TITLE
How to use full path routing for all cultures by default?

### ISSUE THREAD

**Issue by TimCadieux** [saaratrix/asp.net-core-mvc-localized-routing#32]
Currently my startup.cs looks like the below, this works fine however what it does is in the Default culture English, my route is www.site.com whereas when i switch to any other culture I get www.site.com/fr/accuel or www.site.com/es/casa...

How can I get the Default Language to always appear as www.site.com/en/home

startup.cs

// Set up cultures
```
LocalizationRouteDataHandler.DefaultCulture = "en";
LocalizationRouteDataHandler.SupportedCultures = new Dictionary<string, string>()
{
    { "en", "English" },
    { "fr", "Français" },
    { "es", "Español" }
};

```
```

[LocalizationRoute("en", "home")]
[LocalizationRoute("fr", "accueil")]
[LocalizationRoute("es", "casa")]
public class HomeController : LocalizationController
{
    [LocalizationRoute("en", "/home")]
    [LocalizationRoute("fr", "/accueil")]
    [LocalizationRoute("es", "/casa")]
    public IActionResult Index()
    {
        return View();
    }
```

**Comment by saaratrix** [comment]
This one is trickier because there's no default support for forcing `/en` cultures.
The proper answer lies in LocalizationRouteConvention because that's where all the routes are generated.
It needs to add the culture as a prefix to the template but I'm not sure where and it's quite a complex file written 2 years ago. 

When it was written it was not written with your use case in mind.

Alternatively maybe it could be possible to just add `[LocalizationRoute("en", "controllerName")]` for the controllers and then add default culture in the `LocalizationTagHelperUtility` class. 

```cs
if (culture == LocalizationRouteDataHandler.DefaultCulture)
  urlResult = $"{culture}/{urlResult}";

return urlResult;
```

**Comment by TimCadieux** [comment]
Successfully implemented using [this](https://stackoverflow.com/a/57765885/1555453) solution
